from __future__ import annotations

TERMS = {
    "variable": "Espacio de memoria con un nombre que guarda un valor.",
    "función": "Bloque reutilizable de código que realiza una tarea específica.",
    "método": "Función asociada a un objeto o clase.",
    "clase": "Molde que define atributos y comportamientos para crear objetos.",
    "objeto": "Instancia de una clase con estado y comportamiento.",
    "módulo": "Archivo de Python que agrupa código reutilizable.",
    "paquete": "Carpeta con módulos y un __init__.py para organizar código.",
    "parámetro": "Nombre definido en la función para recibir valores.",
    "argumento": "Valor real que se envía a una función al llamarla.",
    "return": "Palabra clave que devuelve un valor desde una función.",
    "none": "Objeto especial que representa ausencia de valor.",
    "bool": "Tipo de dato lógico con valores True o False.",
    "int": "Tipo numérico para enteros.",
    "float": "Tipo numérico para decimales.",
    "str": "Tipo de texto (cadena de caracteres).",
    "list": "Colección ordenada y mutable de elementos.",
    "tuple": "Colección ordenada e inmutable de elementos.",
    "dict": "Colección de pares clave-valor.",
    "set": "Colección de elementos únicos sin orden.",
    "mutable": "Se puede modificar después de ser creado.",
    "inmutable": "No se puede modificar después de ser creado.",
    "iterador": "Objeto que permite recorrer elementos uno a uno.",
    "generador": "Función o expresión que produce valores bajo demanda.",
    "excepción": "Evento que interrumpe el flujo normal por un error.",
    "try": "Bloque para capturar errores potenciales.",
    "except": "Bloque que maneja una excepción específica.",
    "finally": "Bloque que se ejecuta siempre al finalizar un try.",
    "with": "Bloque que gestiona recursos con context manager.",
    "context manager": "Objeto que controla la entrada y salida de un bloque with.",
    "scope": "Alcance donde una variable es visible y válida.",
    "global": "Palabra clave para usar una variable del ámbito global.",
    "local": "Variable definida dentro de un bloque o función.",
    "snake_case": "Convención de nombres con minúsculas y guiones bajos.",
    "pascalcase": "Convención de nombres con cada palabra en mayúscula.",
    "pep8": "Guía de estilo oficial para escribir código Python.",
    "indentación": "Espacios o tabulaciones que delimitan bloques de código.",
    "f-string": "Cadena con interpolación usando prefijo f.",
    "slice": "Subsección de una secuencia usando índices y rango.",
    "comprehension": "Sintaxis compacta para construir colecciones.",
    "append": "Método de listas que agrega un elemento al final.",
    "extend": "Método de listas que agrega varios elementos.",
    "insert": "Método de listas que agrega en una posición específica.",
    "pop": "Método que extrae y devuelve un elemento.",
    "remove": "Método que elimina la primera coincidencia.",
    "sort": "Método que ordena los elementos en su lugar.",
    "upper": "Método de strings que convierte a mayúsculas.",
    "lower": "Método de strings que convierte a minúsculas.",
    "strip": "Método que quita espacios al inicio y final.",
    "split": "Método que separa un string en partes.",
    "join": "Método que une una lista de strings.",
    "replace": "Método que reemplaza subcadenas.",
    "startswith": "Método que comprueba el prefijo.",
    "endswith": "Método que comprueba el sufijo.",
    "get": "Método de dict que devuelve un valor con clave.",
    "items": "Método de dict que devuelve pares clave-valor.",
    "keys": "Método de dict que devuelve las claves.",
    "values": "Método de dict que devuelve los valores.",
    "update": "Método de dict que fusiona valores.",
    "sql": "Lenguaje para consultar y manipular bases de datos relacionales.",
    "cursor": "Objeto que permite recorrer resultados de una consulta.",
    "transacción": "Grupo de operaciones que se confirman o revierten juntas.",
    "commit": "Acción que confirma los cambios pendientes.",
    "rollback": "Acción que revierte los cambios pendientes.",
    "orm": "Técnica que mapea clases de Python a tablas.",
    "engine": "Componente que gestiona la conexión a la base de datos.",
    "session": "Unidad de trabajo que gestiona objetos y transacciones.",
    "pool": "Conjunto de conexiones reutilizables.",
    "dsn": "Cadena que describe cómo conectarse a la base de datos.",
    "sql injection": "Ataque que manipula SQL con datos sin parametrizar.",
}

KEYWORDS = list(TERMS.keys())
